// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ServerMonitoringDbContext))]
    [Migration("20251231120631_AddWatchlistTables")]
    partial class AddWatchlistTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Entities.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AcknowledgedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("AlertRuleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("MonitoredServerId")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AcknowledgedByUserId");

                    b.HasIndex("AlertRuleId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IsAcknowledged");

                    b.HasIndex("MonitoredServerId", "CreatedAtUtc");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("Infrastructure.Entities.AlertRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comparison")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("text");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MonitoredServerId")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TargetId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<double>("ThresholdValue")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("MonitoredServerId", "IsActive");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("Infrastructure.Entities.BackupJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastRunAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastRunStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RepoPasswordEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ScheduleCron")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SshPrivateKeyEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("IsActive");

                    b.HasIndex("AgentId", "IsActive");

                    b.ToTable("BackupJobs");
                });

            modelBuilder.Entity("Infrastructure.Entities.BackupLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DataAdded")
                        .HasColumnType("bigint");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("FilesNew")
                        .HasColumnType("integer");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("SnapshotId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("JobId");

                    b.HasIndex("JobId", "CreatedAtUtc");

                    b.ToTable("BackupLogs");
                });

            modelBuilder.Entity("Infrastructure.Entities.DiskPartitionMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Device")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileSystemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("MetricSampleId")
                        .HasColumnType("bigint");

                    b.Property<string>("MountPoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("TotalGb")
                        .HasColumnType("double precision");

                    b.Property<double>("UsagePercent")
                        .HasColumnType("double precision");

                    b.Property<double>("UsedGb")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MetricSampleId");

                    b.ToTable("DiskPartitionMetrics");
                });

            modelBuilder.Entity("Infrastructure.Entities.MetricSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("CpuUsagePercent")
                        .HasColumnType("double precision");

                    b.Property<double>("DiskReadSpeedMBps")
                        .HasColumnType("double precision");

                    b.Property<double>("DiskWriteSpeedMBps")
                        .HasColumnType("double precision");

                    b.Property<double>("Load15m")
                        .HasColumnType("double precision");

                    b.Property<double>("Load1m")
                        .HasColumnType("double precision");

                    b.Property<double>("Load5m")
                        .HasColumnType("double precision");

                    b.Property<int>("MonitoredServerId")
                        .HasColumnType("integer");

                    b.Property<double>("RamUsagePercent")
                        .HasColumnType("double precision");

                    b.Property<double>("RamUsedGb")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UptimeSeconds")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("MonitoredServerId", "TimestampUtc");

                    b.ToTable("MetricSamples");
                });

            modelBuilder.Entity("Infrastructure.Entities.MonitoredServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Architecture")
                        .HasColumnType("text");

                    b.Property<int?>("CpuCores")
                        .HasColumnType("integer");

                    b.Property<string>("CpuModel")
                        .HasColumnType("text");

                    b.Property<int?>("CpuThreads")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<string>("Kernel")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Os")
                        .HasColumnType("text");

                    b.Property<string>("OsVersion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentToken")
                        .IsUnique();

                    b.HasIndex("Hostname");

                    b.ToTable("MonitoredServers");
                });

            modelBuilder.Entity("Infrastructure.Entities.NetworkInterfaceMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("DownloadSpeedMbps")
                        .HasColumnType("double precision");

                    b.Property<string>("Ipv4")
                        .HasColumnType("text");

                    b.Property<string>("Ipv6")
                        .HasColumnType("text");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("MetricSampleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("UploadSpeedMbps")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MetricSampleId");

                    b.ToTable("NetworkInterfaceMetrics");
                });

            modelBuilder.Entity("Infrastructure.Entities.NotificationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsTelegramEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TelegramBotToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("Infrastructure.Entities.ProcessInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("CpuPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Pid")
                        .HasColumnType("integer");

                    b.Property<long>("ProcessSnapshotId")
                        .HasColumnType("bigint");

                    b.Property<double>("RamMb")
                        .HasColumnType("double precision");

                    b.Property<string>("User")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessSnapshotId");

                    b.ToTable("ProcessInfos");
                });

            modelBuilder.Entity("Infrastructure.Entities.ProcessSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("MonitoredServerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("MonitoredServerId", "TimestampUtc");

                    b.ToTable("ProcessSnapshots");
                });

            modelBuilder.Entity("Infrastructure.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean");

                    b.Property<int>("MonitoredServerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("MonitoredServerId", "Name")
                        .IsUnique();

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Infrastructure.Entities.ServiceStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("ServiceId", "TimestampUtc");

                    b.ToTable("ServiceStatusHistories");
                });

            modelBuilder.Entity("Infrastructure.Entities.TelegramChatId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NotificationSettingsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("NotificationSettingsId");

                    b.ToTable("TelegramChatIds");
                });

            modelBuilder.Entity("Infrastructure.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Infrastructure.Entities.WatchlistProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MonitoredServerId")
                        .HasColumnType("integer");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("MonitoredServerId");

                    b.HasIndex("MonitoredServerId", "ProcessName")
                        .IsUnique();

                    b.ToTable("WatchlistProcesses");
                });

            modelBuilder.Entity("Infrastructure.Entities.WatchlistService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MonitoredServerId")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("MonitoredServerId");

                    b.HasIndex("MonitoredServerId", "ServiceName")
                        .IsUnique();

                    b.ToTable("WatchlistServices");
                });

            modelBuilder.Entity("Infrastructure.Entities.Alert", b =>
                {
                    b.HasOne("Infrastructure.Entities.User", "AcknowledgedByUser")
                        .WithMany("AcknowledgedAlerts")
                        .HasForeignKey("AcknowledgedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Infrastructure.Entities.AlertRule", "AlertRule")
                        .WithMany()
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Infrastructure.Entities.MonitoredServer", "MonitoredServer")
                        .WithMany("Alerts")
                        .HasForeignKey("MonitoredServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcknowledgedByUser");

                    b.Navigation("AlertRule");

                    b.Navigation("MonitoredServer");
                });

            modelBuilder.Entity("Infrastructure.Entities.AlertRule", b =>
                {
                    b.HasOne("Infrastructure.Entities.MonitoredServer", "MonitoredServer")
                        .WithMany()
                        .HasForeignKey("MonitoredServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoredServer");
                });

            modelBuilder.Entity("Infrastructure.Entities.BackupJob", b =>
                {
                    b.HasOne("Infrastructure.Entities.MonitoredServer", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Infrastructure.Entities.BackupLog", b =>
                {
                    b.HasOne("Infrastructure.Entities.BackupJob", "Job")
                        .WithMany("Logs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Infrastructure.Entities.DiskPartitionMetric", b =>
                {
                    b.HasOne("Infrastructure.Entities.MetricSample", "MetricSample")
                        .WithMany("DiskPartitions")
                        .HasForeignKey("MetricSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetricSample");
                });

            modelBuilder.Entity("Infrastructure.Entities.MetricSample", b =>
                {
                    b.HasOne("Infrastructure.Entities.MonitoredServer", "MonitoredServer")
                        .WithMany("Metrics")
                        .HasForeignKey("MonitoredServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoredServer");
                });

            modelBuilder.Entity("Infrastructure.Entities.NetworkInterfaceMetric", b =>
                {
                    b.HasOne("Infrastructure.Entities.MetricSample", "MetricSample")
                        .WithMany("NetworkInterfaces")
                        .HasForeignKey("MetricSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetricSample");
                });

            modelBuilder.Entity("Infrastructure.Entities.ProcessInfo", b =>
                {
                    b.HasOne("Infrastructure.Entities.ProcessSnapshot", "ProcessSnapshot")
                        .WithMany("Processes")
                        .HasForeignKey("ProcessSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessSnapshot");
                });

            modelBuilder.Entity("Infrastructure.Entities.ProcessSnapshot", b =>
                {
                    b.HasOne("Infrastructure.Entities.MonitoredServer", "MonitoredServer")
                        .WithMany("ProcessSnapshots")
                        .HasForeignKey("MonitoredServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoredServer");
                });

            modelBuilder.Entity("Infrastructure.Entities.Service", b =>
                {
                    b.HasOne("Infrastructure.Entities.MonitoredServer", "MonitoredServer")
                        .WithMany("Services")
                        .HasForeignKey("MonitoredServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoredServer");
                });

            modelBuilder.Entity("Infrastructure.Entities.ServiceStatusHistory", b =>
                {
                    b.HasOne("Infrastructure.Entities.Service", "Service")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Infrastructure.Entities.TelegramChatId", b =>
                {
                    b.HasOne("Infrastructure.Entities.NotificationSettings", "NotificationSettings")
                        .WithMany("TelegramChatIds")
                        .HasForeignKey("NotificationSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationSettings");
                });

            modelBuilder.Entity("Infrastructure.Entities.WatchlistProcess", b =>
                {
                    b.HasOne("Infrastructure.Entities.MonitoredServer", "MonitoredServer")
                        .WithMany()
                        .HasForeignKey("MonitoredServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoredServer");
                });

            modelBuilder.Entity("Infrastructure.Entities.WatchlistService", b =>
                {
                    b.HasOne("Infrastructure.Entities.MonitoredServer", "MonitoredServer")
                        .WithMany()
                        .HasForeignKey("MonitoredServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoredServer");
                });

            modelBuilder.Entity("Infrastructure.Entities.BackupJob", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Infrastructure.Entities.MetricSample", b =>
                {
                    b.Navigation("DiskPartitions");

                    b.Navigation("NetworkInterfaces");
                });

            modelBuilder.Entity("Infrastructure.Entities.MonitoredServer", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Metrics");

                    b.Navigation("ProcessSnapshots");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Infrastructure.Entities.NotificationSettings", b =>
                {
                    b.Navigation("TelegramChatIds");
                });

            modelBuilder.Entity("Infrastructure.Entities.ProcessSnapshot", b =>
                {
                    b.Navigation("Processes");
                });

            modelBuilder.Entity("Infrastructure.Entities.Service", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Infrastructure.Entities.User", b =>
                {
                    b.Navigation("AcknowledgedAlerts");
                });
#pragma warning restore 612, 618
        }
    }
}
